// <auto-generated />
using System;
using AngularWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularWebApi.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20200410072136_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularWebApi.Models.Customer", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CDob")
                        .HasColumnType("datetime2");

                    b.Property<string>("CName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CPin")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.HasKey("CId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CId = 1,
                            CDob = new DateTime(2019, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CName = "Palak",
                            CPin = 1001
                        },
                        new
                        {
                            CId = 2,
                            CDob = new DateTime(2019, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CName = "Kareena",
                            CPin = 1002
                        },
                        new
                        {
                            CId = 3,
                            CDob = new DateTime(2019, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CName = "Pushp",
                            CPin = 1003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
